### ISSUE TITLE
64-bit build?

### ISSUE THREAD

**Issue by johngrasty** [pmazaitis/ConTeXtBBLM#1]
Hello,

It looks like this is a great BBLM, but unfortunately it won't run on BBEdit 12 on my machine. It looks like the problem is architecture, but I really don't know. Here's the error from the console:

```
Error loading /Users/jgrasty/Library/Application Support/BBEdit/Language Modules/ConTeXt-v1.4.bblm/Contents/MacOS/ConTeXt:  dlopen(/Users/jgrasty/Library/Application Support/BBEdit/Language Modules/ConTeXt-v1.4.bblm/Contents/MacOS/ConTeXt, 262): no suitable image found.  Did find:
	/Users/jgrasty/Library/Application Support/BBEdit/Language Modules/ConTeXt-v1.4.bblm/Contents/MacOS/ConTeXt: mach-o, but wrong architecture
	/Users/jgrasty/Library/Application Support/BBEdit/Language Modules/ConTeXt-v1.4.bblm/Contents/MacOS/ConTeXt: mach-o, but wrong architecture
```

**Comment by tflo** [comment]
Barebones has announced the upcoming incompatibility with old modules in December, and BBEdit 12.1(410023) from 29 January was the first “64bit” BBEdit.

So, yes, it seems this is related.

– Tom

**Comment by pm39** [comment]
Indeed! I have a development version of the API from a while back that I've been trying to build the BBLM against, but I've been having troubles with it; I have a gap in the calendar next week to work on this, and I'm checking now to see if there's an updated API (and if the folks at Bare Bones have any other suggestions).

(There is certainly impetus for me here, as well; I've been nervously maintaining a copy of BBEdit 11 for ConTeXt work, and I'd like to stop doing that. :) )

**Comment by johngrasty** [comment]
That’s great to hear. Unfortunately it is beyond my ability to help!! I hope you are successful!
